
positive_words = [
    'accessible', 'acclaimed', 'accomplish', 'accomplished', 'achievement', 'active', 'admirable', 'admire', 'adorable', 'advantage',
    'adventurous', 'agreeable', 'alive', 'amazing', 'amiable', 'amusing', 'angelic', 'appealing', 'appreciate', 'appreciated',
    'approachable', 'approve', 'approved', 'ardent', 'aspire', 'assured', 'astonishing', 'astounding', 'attentive', 'attractive',
    'audacious', 'authentic', 'authority', 'awaken', 'awesome', 'balanced', 'beautiful', 'beauty', 'beloved', 'beneficial',
    'benevolent', 'best', 'bless', 'bliss', 'blissful', 'bloom', 'blossom', 'bold', 'bountiful', 'brave',
    'bravery', 'brilliant', 'calm', 'capable', 'captivate', 'carefree', 'caring', 'celebrate', 'celebrated', 'certain',
    'charming', 'cheer', 'cheerful', 'cherish', 'choice', 'clarity', 'classic', 'clean', 'clever', 'colorful',
    'comfort', 'comfortable', 'commendable', 'commit', 'committed', 'compassion', 'compassionate', 'competent', 'complete', 'confident',
    'congratulate', 'congratulations', 'conscientious', 'considerate', 'consistent', 'constant', 'content', 'cool', 'courage', 'courageous',
    'courteous', 'creative', 'credible', 'cure', 'cushy', 'dazzling', 'decisive', 'dedicated', 'delight', 'delighted',
    'dependable', 'desirable', 'determine', 'determined', 'devoted', 'diligent', 'discipline', 'discover', 'distinction', 'dream',
    'durable', 'eager', 'earnest', 'ease', 'easy', 'ecstasy', 'ecstatic', 'effective', 'effortless', 'efficient',
    'elegance', 'elegant', 'eloquent', 'empower', 'enchanting', 'encourage', 'encouraging', 'endearing', 'endless', 'energetic',
    'energy', 'engage', 'engaging', 'enjoy', 'enjoyable', 'enlighten', 'enormous', 'enough', 'enthusiasm', 'enthusiastic',
    'epitome', 'essential', 'esteem', 'eternal', 'excellent', 'excited', 'exciting', 'exquisite', 'extraordinary', 'exuberant',
    'fabulous', 'fair', 'fairness', 'faithful', 'fame', 'famed', 'family', 'famous', 'fancy', 'fantastic',
    'fascinating', 'favorable', 'favorite', 'fearless', 'fiery', 'fine', 'first-class', 'flawless', 'flourish', 'fond',
    'forgiving', 'fortunate', 'fortune', 'free', 'freedom', 'fresh', 'friendly', 'friendship', 'frugal', 'fulfill',
    'full', 'fun', 'funny', 'gallant', 'generous', 'gentle', 'genuine', 'gifted', 'giving', 'glad',
    'glorious', 'glory', 'glowing', 'godsend', 'good', 'gorgeous', 'grace', 'graceful', 'grateful', 'gratitude',
    'great', 'growth', 'guaranteed', 'guidance', 'gutsy', 'happy', 'harmony', 'heal', 'healing', 'healthy',
    'heartfelt', 'heavenly', 'help', 'helpful', 'hero', 'heroic', 'high-class', 'holy', 'honest', 'honesty',
    'honor', 'honorable', 'hope', 'hopeful', 'humble', 'humor', 'ideal', 'imagine', 'imaginative', 'impartial',
    'impressive', 'improve', 'improved', 'incredible', 'infallible', 'infinite', 'influence', 'influential', 'ingenuity', 'innocent',
    'innovate', 'innovative', 'inspiration', 'inspired', 'inspiring', 'integrity', 'intelligent', 'intensity', 'interact', 'interesting',
    'intimate', 'invincible', 'inviting', 'joy', 'joyful', 'jubilant', 'keen', 'key', 'kind', 'kindness',
    'knowledge', 'knowledgeable', 'kudos', 'laugh', 'laughing', 'lavish', 'leader', 'leading', 'legendary', 'leisure',
    'lenient', 'level-headed', 'liberating', 'light', 'likable', 'like', 'love', 'lovely', 'loving', 'loyal',
    'loyalty', 'lucid', 'lucky', 'magnificent', 'majestic', 'major', 'marvelous', 'masterful', 'masterpiece', 'meaningful',
    'meditative', 'mellow', 'memorable', 'mend', 'merciful', 'mercy', 'merit', 'meritorious', 'merry', 'miracle',
    'miraculous', 'moderate', 'modest', 'motivate', 'motivated', 'movement', 'natural', 'needed', 'noble', 'nourish',
    'novel', 'nurture', 'obedient', 'objective', 'open', 'open-minded', 'optimistic', 'original', 'outstanding', 'overcome',
    'paradise', 'patience', 'patient', 'peace', 'peaceful', 'perfect', 'perfection', 'perseverance', 'persistent', 'phenomenal',
    'picturesque', 'pioneering', 'pleasant', 'please', 'pleased', 'pleasure', 'plentiful', 'poised', 'polished', 'popular',
    'positive', 'powerful', 'praise', 'precious', 'precise', 'premium', 'prepare', 'prepared', 'priceless', 'proactive',
    'productive', 'proficient', 'profit', 'progress', 'promising', 'promote', 'prompt', 'prosper', 'prosperous', 'proud',
    'pure', 'purposeful', 'quality', 'quick', 'quiet', 'radiant', 'rapport', 'rational', 'ready', 'reassuring',
    'receptive', 'recognize', 'recommend', 'recover', 'refresh', 'refreshed', 'regal', 'rejoice', 'relaxed', 'relief',
    'relieve', 'remarkable', 'renewed', 'resilient', 'respect', 'respectable', 'resourceful', 'restful', 'revere', 'reward',
    'rewarding', 'rich', 'righteous', 'robust', 'rose', 'safe', 'safety', 'sage', 'satisfaction', 'satisfied',
    'savvy', 'secure', 'self-assured', 'sensational', 'sense', 'serene', 'serenity', 'sharp', 'shine', 'sincere',
    'skillful', 'smile', 'smooth', 'solace', 'solid', 'sparkle', 'special', 'spectacular', 'spirit', 'spiritual',
    'splendid', 'stable', 'stamina', 'steady', 'strong', 'stunning', 'succeed', 'success', 'successful', 'sufficient',
    'suitable', 'super', 'superb', 'superior', 'support', 'supportive', 'sure', 'surprise', 'sweet', 'sympathetic',
    'talent', 'talented', 'tenderness', 'thankful', 'thorough', 'thrive', 'thrill', 'thrilled', 'tidy', 'timeless',
    'tolerance', 'top-notch', 'tough', 'tranquil', 'tranquility', 'transform', 'trust', 'trusting', 'truth', 'truthful',
    'understand', 'understanding', 'unforgettable', 'unify', 'unique', 'unselfish', 'upbeat', 'useful', 'valiant', 'valuable',
    'value', 'vibrant', 'victory', 'vigilant', 'virtue', 'virtuous', 'vision', 'vital', 'vivid', 'warm',
    'welcome', 'well-being', 'whole', 'wholesome', 'willing', 'win', 'wise', 'wisdom', 'wonderful', 'wonderfully',
    'winning', 'wondrous', 'worth', 'worthwhile', 'worthy', 'wow', 'zest', 'zesty', 'zippy'
]

